[package]
name = "mandelbrot-core"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
palette = "0.4"
safe-transmute = "0.11.0-rc.2"
wasm-bindgen = "0.2.44"
