version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest-node
    working_directory: ~/repo
    steps:
      - checkout
      - run: script/setup
      - run: script/build
      - run: script/deploy
