[package]
name = "mandelbrot-desktop"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"

[dependencies]
mandelbrot-core = { path = "../mandelbrot-core" }
minifb = "0.11.2"
